#Once-off (can potentially be a harmful command, use with caution):
#xhost +local:docker
#xhost -local:docker


version: '3'
services:
  pycharm:
    container_name: pycharm
    network_mode: host
    build: .
    environment:
      - DISPLAY=$DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - filestore:/opt/filestore/filestore
      - odoo120:/opt/odoo
volumes:
  odoo120:
  filestore:
